language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy"
install:
  - pip install --no-cache -r requirements-test.txt
  - pip install --no-cache -r requirements.txt
  - pip install -e .
script:
  - pytest tests
after_success:
  - coveralls
services: mongodb
